### ISSUE TITLE
can't send cards to yourself

### ISSUE THREAD

**Issue by micimize** [micimize/chizukeki#8]
If sending cards to your own address is an invalid action, it should be disallowed.
If it is valid, it should succeed

**Comment by peerchemist** [comment]
In PeerAssets protocol sending card back to the address which spawned the deck is a card burn transaction which removes the cards from circulation. Sending card from your address to your address again is perfectly fine and it is allowed.

**Comment by micimize** [comment]
this was due to papi being out of sync. Hard to detect when it is - we could add a `/lastseen` to papi and compare block heights, but really this is further convincing me of the utility a reworked (graphql) backend that synthesizes the explorer and asset data would be.
